load("//defs.bzl", "global_compiler_flags")
load("//defs.bzl", "global_linker_flags")

cxx_library(
    name = "headers",
    visibility = ["PUBLIC"],
    header_namespace = "",
    exported_headers = [
        "angelscript.h",
    ],
    compiler_flags = global_compiler_flags,
    linker_flags = global_linker_flags,
    link_style = "static",
)
